---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/wokober/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp get_involved.html $DEPLOYPATH
    - /bin/cp tf-2022.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R videos $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH